"""Build and validate the Python/JIT sdist and wheel; never publish packages."""

import argparse
import base64
import hashlib
import importlib.metadata
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import venv
import zipfile
from email.parser import BytesParser
from pathlib import Path

SOURCE_SUFFIXES = {".py", ".cpp", ".cu", ".h", ".cuh", ".cc", ".tr", ".pyi"}
BINARY_SUFFIXES = {".so", ".pyd", ".dll", ".dylib"}


def check_installed(manifest_path):
    """Run in an isolated venv without importing ColossalAI or its dependencies."""
    manifest = json.loads(Path(manifest_path).read_text())
    distribution = importlib.metadata.distribution(manifest["name"])
    if distribution.version != manifest["version"]:
        raise RuntimeError("The installed distribution has the wrong version")
    records = {str(path): path for path in distribution.files or []}
    for name, expected_hash in manifest["files"].items():
        if name not in records:
            raise RuntimeError(f"Installed RECORD is missing {name}")
        record = records[name]
        data = distribution.locate_file(record).read_bytes()
        if hashlib.sha256(data).hexdigest() != expected_hash:
            raise RuntimeError(f"Installed source differs from the checkout: {name}")
        encoded_hash = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=").decode()
        if record.hash is None or record.hash.mode != "sha256" or record.hash.value != encoded_hash:
            raise RuntimeError(f"Installed RECORD has an invalid hash for {name}")
    print(
        f"Verified installed metadata and RECORD for {len(manifest['files'])} source files; dependencies not installed"
    )


def source_inventory(root):
    inventory = {}
    # Enumerate sources independently of setuptools' package finder, including namespaces.
    # version.py is generated by setup.py and validated against package metadata separately.
    for path in (root / "colossalai").rglob("*.py"):
        relative = path.relative_to(root).as_posix()
        if relative != "colossalai/version.py":
            inventory[relative] = path.read_bytes()
    # pathlib does not follow the kernel/extensions symlink on every supported Python version.
    for path in (root / "extensions").rglob("*"):
        if path.is_file() and path.suffix in SOURCE_SUFFIXES:
            relative = path.relative_to(root / "extensions")
            inventory[f"colossalai/kernel/extensions/{relative.as_posix()}"] = path.read_bytes()
    for suffix in (".py", ".cpp", ".cu", ".h", ".cuh"):
        if not any(name.endswith(suffix) for name in inventory):
            raise RuntimeError(f"The checkout contains no expected {suffix} sources")
    return inventory


def verify_artifacts(output, inventory):
    from packaging.utils import canonicalize_name, parse_sdist_filename, parse_wheel_filename
    from packaging.version import Version

    wheels = list(output.glob("*.whl"))
    sdists = list(output.glob("*.tar.gz"))
    if len(wheels) != 1 or len(sdists) != 1 or len(list(output.iterdir())) != 2:
        raise RuntimeError("Expected exactly one wheel and one sdist")
    wheel, sdist = wheels[0], sdists[0]
    with zipfile.ZipFile(wheel) as archive:
        names = set(archive.namelist())
        binaries = [name for name in names if Path(name).suffix in BINARY_SUFFIXES]
        if binaries:
            raise RuntimeError(f"Unexpected compiled extensions in the Python/JIT wheel: {binaries}")
        for name, expected in inventory.items():
            if name not in names or archive.read(name) != expected:
                raise RuntimeError(f"Wheel source is absent or differs from the checkout: {name}")
        unexpected_python = sorted(
            name for name in names if name.endswith(".py") and name not in inventory and name != "colossalai/version.py"
        )
        if unexpected_python:
            raise RuntimeError(f"Unexpected Python modules in the wheel: {unexpected_python}")
        metadata_paths = [name for name in names if name.endswith(".dist-info/METADATA")]
        if len(metadata_paths) != 1:
            raise RuntimeError("Expected one wheel metadata directory")
        metadata_path = metadata_paths[0]
        metadata = BytesParser().parsebytes(archive.read(metadata_path))
        wheel_name, wheel_version, _, _ = parse_wheel_filename(wheel.name)
        sdist_name, sdist_version = parse_sdist_filename(sdist.name)
        if canonicalize_name(metadata["Name"]) != wheel_name or wheel_name != sdist_name:
            raise RuntimeError("Distribution names do not match the wheel metadata")
        if Version(metadata["Version"]) != wheel_version or wheel_version != sdist_version:
            raise RuntimeError("Distribution versions do not match the wheel metadata")
        version_path = "colossalai/version.py"
        if version_path not in names:
            raise RuntimeError("The wheel is missing the generated runtime version module")
        version_source = archive.read(version_path)
        version_match = re.fullmatch(r"\s*__version__\s*=\s*(['\"])([^'\"]+)\1\s*", version_source.decode())
        if version_match is None or Version(version_match[2]) != wheel_version:
            raise RuntimeError("The runtime version module does not match the wheel metadata")
        wheel_metadata = BytesParser().parsebytes(archive.read(metadata_path.replace("METADATA", "WHEEL")))
        if wheel_metadata["Root-Is-Purelib"] != "true" or wheel_metadata.get_all("Tag") != ["py3-none-any"]:
            raise RuntimeError("Expected a pure Python wheel with py3-none-any tag")
        if metadata_path.replace("METADATA", "RECORD") not in names:
            raise RuntimeError("The wheel contains no RECORD")
    with tarfile.open(sdist, "r:gz") as archive:
        members = archive.getmembers()
        roots = {Path(member.name).parts[0] for member in members}
        if len(roots) != 1:
            raise RuntimeError("Expected one sdist root directory")
        prefix = roots.pop()
        for name, expected in {**inventory, version_path: version_source}.items():
            # The top-level extensions directory is needed when building from source.
            relative = name.replace("colossalai/kernel/extensions/", "extensions/", 1)
            source = archive.extractfile(f"{prefix}/{relative}")
            if source is None or source.read() != expected:
                raise RuntimeError(f"Source distribution is missing {relative}")
        for relative in ("setup.py", "version.txt", "requirements/requirements.txt"):
            if archive.extractfile(f"{prefix}/{relative}") is None:
                raise RuntimeError(f"Source distribution is missing {relative}")
        source_version = archive.extractfile(f"{prefix}/version.txt").read().decode().strip()
        if Version(source_version) != wheel_version:
            raise RuntimeError("The source version.txt does not match the wheel metadata")
        source_metadata = BytesParser().parsebytes(archive.extractfile(f"{prefix}/PKG-INFO").read())
        if (
            canonicalize_name(source_metadata["Name"]) != wheel_name
            or Version(source_metadata["Version"]) != wheel_version
        ):
            raise RuntimeError("The sdist metadata does not match the wheel metadata")
    print(f"Verified {wheel.name} and {sdist.name}: {len(inventory)} Python/JIT source files, no prebuilt extensions")
    return wheel, sdist, metadata, version_source


def build(root, output):
    if output.exists() and (not output.is_dir() or any(output.iterdir())):
        raise RuntimeError(f"Output must be absent or empty to prevent publishing stale artifacts: {output}")
    inventory = source_inventory(root)
    with tempfile.TemporaryDirectory(prefix="colossal-python-package-") as temporary:
        temporary = Path(temporary)
        staging = temporary / "dist"
        env = os.environ.copy()
        env["BUILD_EXT"] = "0"
        # With neither --sdist nor --wheel, build makes an sdist and builds the wheel from it.
        subprocess.run(
            [
                sys.executable,
                "-m",
                "build",
                "--no-isolation",
                "--outdir",
                str(staging),
                str(root),
            ],
            env=env,
            check=True,
        )
        wheel, sdist, metadata, version_source = verify_artifacts(staging, inventory)
        inventory["colossalai/version.py"] = version_source
        manifest = temporary / "installed-sources.json"
        manifest.write_text(
            json.dumps(
                {
                    "name": metadata["Name"],
                    "version": metadata["Version"],
                    "files": {name: hashlib.sha256(data).hexdigest() for name, data in inventory.items()},
                }
            )
        )
        install_env = temporary / "install-venv"
        venv.EnvBuilder(with_pip=True).create(install_env)
        install_python = install_env / "bin" / "python"
        subprocess.run(
            [
                str(install_python),
                "-I",
                "-m",
                "pip",
                "install",
                "--no-deps",
                "--no-index",
                str(wheel),
            ],
            cwd=temporary,
            check=True,
        )
        subprocess.run(
            [
                str(install_python),
                "-I",
                str(Path(__file__).resolve()),
                "--verify-installed-manifest",
                str(manifest),
            ],
            cwd=temporary,
            check=True,
        )
        output.mkdir(parents=True, exist_ok=True)
        if any(output.iterdir()):
            raise RuntimeError(f"Output changed while building; refusing to mix artifacts: {output}")
        for artifact in (wheel, sdist):
            shutil.copy2(artifact, output / artifact.name)
    print(f"Validated Python/JIT distributions are ready in {output}; no GPU execution was tested")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("dist"))
    parser.add_argument("--verify-installed-manifest", type=Path, help=argparse.SUPPRESS)
    args = parser.parse_args()
    if args.verify_installed_manifest:
        check_installed(args.verify_installed_manifest)
    else:
        root = Path(__file__).resolve().parents[3]
        build(root, args.output_dir.resolve())


if __name__ == "__main__":
    main()
